# netty configuration
netty:
  port: 10100
  threads:
    worker: 4
    acceptor: 2
    isCoreBased: false
  backlog: 100
  report: true

# logging level
logging:
  level:
    org:
      springframework: info
    io:
      netty: debug
    com:
      gompang: info
